# Generated by Django 4.1.7 on 2023-03-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0006_subject_alter_course_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='descr',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
