# Generated by Django 4.1.7 on 2023-04-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0012_user_shopping_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, null=True, to='schedule_advisor.course'),
        ),
    ]
