# Generated by Django 4.1.7 on 2023-04-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0013_remove_user_shopping_cart_user_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(to='schedule_advisor.course'),
        ),
    ]
