# Generated by Django 4.1.7 on 2023-04-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0016_user_statues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='statues',
            new_name='status',
        ),
    ]
