# Generated by Django 4.1.7 on 2023-02-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
    ]
