# Generated by Django 4.1.7 on 2023-03-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0004_instructor_meeting_remove_course_days_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='schedule_advisor_course_unique',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('term', 'class_nbr', 'subject', 'catalog_number'), name='schedule_advisor_course_unique'),
        ),
    ]
