# Generated by Django 4.1.7 on 2023-03-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0005_remove_course_schedule_advisor_course_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
