# Generated by Django 4.1.7 on 2023-03-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0008_course_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_nbr',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
