# Generated by Django 4.1.7 on 2023-03-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0009_alter_course_class_nbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_section',
            field=models.CharField(default='', max_length=20),
        ),
    ]
