# Generated by Django 4.1.7 on 2023-04-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0010_alter_course_class_section'),
        ('schedule_advisor', '0010_shoppingcart'),
    ]

    operations = [
    ]
