# Generated by Django 4.1.7 on 2023-04-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0014_alter_user_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
