# Generated by Django 4.1.7 on 2023-04-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0015_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='statues',
            field=models.IntegerField(default=0),
        ),
    ]
