# Generated by Django 4.1.7 on 2023-04-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0017_rename_statues_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='st_time',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
