# Generated by Django 4.1.7 on 2023-04-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0018_alter_meeting_end_time_alter_meeting_st_time'),
        ('schedule_advisor', '0018_alter_user_status'),
    ]

    operations = [
    ]
